

# [[main]]
#     # Top-level menu entry
#     identifier = "writing"
#     name = "PLCT-Weekly"
#     url = "/en/posts/plct-weekly/"
#     weight = 4

# [[main]]
#     identifier = "News"
#     name = "News"
#     url = "/zh/news/"
#     weight = 4
